Stop grace period is set to 5 min
PeterGrace/opentsdb-docker pull request #36
Opened 2019-05-02 11:57 UTC by pgillich

Stop grace period is increased to 5 min in the compose config files. Description is also updated.

2019-05-02 12:03 UTC, pgillich commented
The WAITSECS=30 might also be changed?

2020-12-05 14:49 UTC, PeterGrace requested changes
Thanks for your PR @pgillich and sorry it took so long to respond.  GitHub notifications seldom seem to work right for me and I wind up discovering people have left PRs mostly by accident.  I've left some comments, if you are still interested in this PR can we discuss my comments?

2020-12-05 14:49 UTC, PeterGrace commented on files/opentsdb.conf
> +tsd.core.meta.enable_realtime_ts = true
This addition is a bit beyond the scope of the demonstration docker container -- the help text read:

> As every data points spawns an increment request, this can generate a much larger load in a TSD and chew up heap space pretty quickly so only enable this if you can spread the load across multiple TSDs or your writes are fairly small.

As such, I am not in favor of adding this by default.

2020-12-05 14:49 UTC, PeterGrace commented on downloads/help.txt
> +cd /opt/downloads/201812
I'm assuming this was added accidentally as it seems to be part of your local environment setup.  This should probably not be part of the PR.

2024-07-18 17:11 UTC, PeterGrace commented
Thanks so much for your PR suggestion.  I am archiving this repo as it seems no longer relevant in today's environment.

2024-07-18 17:11 UTC, closed without merging